'use strict';
const building=window.BUILDING,$=id=>document.getElementById(id),nodes=new Map(building.nodes.map(n=>[n.id,n]));
let floor=1,route=null,scale=1;
const places=building.nodes.filter(n=>['room','entrance'].includes(n.kind));
for(const n of places){const o=document.createElement('option');o.value=n.id;o.label=`${n.label} · ${n.floor} этаж`;$('places').append(o);}
for(const s of building.sources){const p=document.createElement('p'),a=document.createElement('a');a.href=s.url;a.textContent=s.id==='cabs'?'Перечень аудиторий ТулГУ':s.id==='2gis'?'Карточка 2ГИС':'Страница корпуса ТулГУ';a.target='_blank';a.rel='noopener';p.append(a,document.createTextNode(' — '+s.supports));$('sources').append(p);}
function svg(tag,attrs={},text){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text)e.textContent=text;return e;}
function render(){
 $('floor-title').textContent=floor+' этаж';$('floors').replaceChildren();
 for(const f of building.floors){const b=document.createElement('button');b.textContent=f;b.setAttribute('aria-label',f+' этаж');b.setAttribute('aria-pressed',f===floor);if(route?.path.some(id=>nodes.get(id).floor===f))b.className='on-route';b.onclick=()=>{floor=f;render();};$('floors').append(b);}
 const map=$('map');map.replaceChildren(svg('title',{id:'map-title'},`Демонстрационная схема: ${floor} этаж`));const ns=building.nodes.filter(n=>n.floor===floor),width=Math.max(800,...ns.map(n=>n.x+100));map.setAttribute('viewBox',`0 0 ${width} 460`);map.style.width=`${width*scale}px`;
 const cs=ns.filter(n=>n.kind==='corridor');map.append(svg('rect',{x:70,y:220,width:width-140,height:60,rx:8,fill:'#e2ebf2'}));map.append(svg('text',{x:width/2,y:425,'text-anchor':'middle'},'УСЛОВНАЯ ГЕОМЕТРИЯ · ТРЕБУЕТ ОБМЕРА'));
 for(const e of building.edges){const a=nodes.get(e.a),b=nodes.get(e.b);if(a.floor===floor&&b.floor===floor)map.append(svg('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:'#a6bbc9','stroke-width':2}));}
 if(route)for(let i=1;i<route.path.length;i++){const a=nodes.get(route.path[i-1]),b=nodes.get(route.path[i]);if(a.floor===floor&&b.floor===floor)map.append(svg('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:'#1265bd','stroke-width':7,'stroke-linecap':'round'}));}
 for(const n of ns){if(n.kind==='corridor')continue;const g=svg('g',{class:'point',tabindex:0,role:'button','aria-label':n.label});const selected=route?.path.includes(n.id);if(n.kind==='room'){g.append(svg('rect',{x:n.x-24,y:n.y-27,width:48,height:54,rx:5,class:'room-shape'+(selected?' selected':'')}));g.append(svg('text',{x:n.x,y:n.y+5,'text-anchor':'middle'},n.id));}else{g.append(svg('circle',{cx:n.x,cy:n.y,r:19,fill:selected?'#1265bd':'#284c65'}));const t=svg('text',{x:n.x,y:n.y+5,'text-anchor':'middle'},n.kind==='entrance'?'В':n.id[1]==='A'?'А':'Б');t.style.fill='white';g.append(t);}
 const choose=()=>{if(n.kind==='stairs')return;$($('pick').value).value=n.id;route=null;$('result').textContent='Точка выбрана. Постройте маршрут.';$('steps').replaceChildren();render();};g.onclick=choose;g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}};map.append(g);
 }
 if(route){for(const [i,id]of route.path.entries()){const n=nodes.get(id);if(n.floor===floor&&(i===0||i===route.path.length-1))map.append(svg('text',{x:n.x,y:n.y-38,'text-anchor':'middle'},i===0?'СТАРТ':'ФИНИШ'));}}
}
function calculate(e){e?.preventDefault();const a=$('from').value.trim().toLowerCase(),b=$('to').value.trim().toLowerCase();$('steps').replaceChildren();if(!places.some(n=>n.id===a)||!places.some(n=>n.id===b)){route=null;$('result').textContent='Выберите номер из списка. Неизвестные аудитории пока не нанесены.';render();return;}route=shortestPath(building.nodes,building.edges,a,b);if(!route){$('result').textContent='Путь не найден: проверьте соединения графа.';render();return;}floor=nodes.get(a).floor;$('result').textContent=a===b?'Вы уже в выбранной точке.':`Маршрут ${a} → ${b}. Стоимость: ${route.cost} усл. ед. Все проходы требуют проверки.`;
 const li=document.createElement('li');li.textContent=`Начните: ${nodes.get(a).label}, ${floor} этаж`;$('steps').append(li);
 let lastFloor=floor;for(const id of route.path){const n=nodes.get(id);if(n.floor!==lastFloor){const item=document.createElement('li'),btn=document.createElement('button');item.append(document.createTextNode(`По условной лестнице ${id[1]==='A'?'А':'Б'} на ${n.floor} этаж. `));btn.textContent='Показать этаж';btn.onclick=()=>{floor=n.floor;render();};item.append(btn);$('steps').append(item);lastFloor=n.floor;}}
 if(a!==b){const end=document.createElement('li');end.textContent=`По коридору к точке: ${nodes.get(b).label}`;$('steps').append(end);}render();}
$('route-form').onsubmit=calculate;$('swap').onclick=()=>{const a=$('from').value;$('from').value=$('to').value;$('to').value=a;calculate();};for(const id of ['from','to'])$(id).oninput=()=>{route=null;$('result').textContent='Постройте маршрут для новых точек.';$('steps').replaceChildren();render();};$('plus').onclick=()=>{scale=Math.min(3,scale+.25);render();};$('minus').onclick=()=>{scale=Math.max(.5,scale-.25);render();};$('reset').onclick=()=>{scale=1;render();};calculate();
